name: Create Jira Issue from Dependabot Alert

on:
  workflow_dispatch:
    inputs:
      project:
        required: true
        type: string
      port_context:
        required: true
        type: string

jobs:
  create-jira-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Map severity to priority
        id: map_priority
        run: |
          if [[ "${{ fromJson(inputs.port_context).entity.properties.severity }}" == "low" ]]; then
            echo "priority_name=Low" >> $GITHUB_ENV
          elif [[ "${{ fromJson(inputs.port_context).entity.properties.severity }}" == "medium" ]]; then
            echo "priority_name=Medium" >> $GITHUB_ENV
          elif [[ "${{ fromJson(inputs.port_context).entity.properties.severity }}" == "high" ]]; then
            echo "priority_name=High" >> $GITHUB_ENV
          elif [[ "${{ fromJson(inputs.port_context).entity.properties.severity }}" == "critical" ]]; then
            echo "priority_name=Critical" >> $GITHUB_ENV
          else
            echo "priority_name=Medium" >> $GITHUB_ENV  # Default to Medium if severity is not recognized
          fi

      - name: Inform starting of Jira issue creation
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).run_id }}
          logMessage: "Creating a new Jira issue from Dependabot alert... ⛴️"

      - name: Create Jira issue
        id: create_jira
        uses: atlassian/gajira-create@v3
        with:
          project: ${{ inputs.project }}
          issuetype: Bug  # Adjust as needed
          summary: "Dependabot Alert: ${{ fromJson(inputs.port_context).entity.properties.packageName }}"
          description: |
            **Severity**: ${{ fromJson(inputs.port_context).entity.properties.severity }}
            **State**: ${{ fromJson(inputs.port_context).entity.properties.state }}
            **Package Name**: ${{ fromJson(inputs.port_context).entity.properties.packageName }}
            **Package Ecosystem**: ${{ fromJson(inputs.port_context).entity.properties.packageEcosystem }}
            **Manifest Path**: ${{ fromJson(inputs.port_context).entity.properties.manifestPath }}
            **Scope**: ${{ fromJson(inputs.port_context).entity.properties.scope }}
            **GHSA ID**: ${{ fromJson(inputs.port_context).entity.properties.ghsaID }}
            **CVE ID**: ${{ fromJson(inputs.port_context).entity.properties.cveID }}
            **URL**: ${{ fromJson(inputs.port_context).entity.properties.url }}
            **References**:
            ${{ join(fromJson(inputs.port_context).entity.properties.references, '\n            ') }}
          fields: |
            {
              "priority": {"name": "${{ env.priority_name }}"},
              "labels": ["port-${{ fromJson(inputs.port_context).entity.identifier }}"]
            }

      - name: Inform creation of Jira issue
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          link: ${{ secrets.JIRA_BASE_URL }}/browse/${{ steps.create_jira.outputs.issue }}
          runId: ${{ fromJson(inputs.port_context).run_id }}
          logMessage: |
            Jira issue created! ✅
            The issue ID is: ${{ steps.create_jira.outputs.issue }}
